### ISSUE TITLE
where to fine dataset?

### ISSUE THREAD

**Issue by dongqi-me** [brijeshiitg/Pytorch-implementation-of-SRNet#11]
COVER_PATH = '/path/to/cover/images/'
STEGO_PATH = '/path/to/stego/images/'

may i know where you place your dataset? thanks

**Comment by brijeshiitg** [comment]
You can find cover images here: [BOSSbase_1.01.zip](https://dde.binghamton.edu/download/ImageDB/BOSSbase_1.01.zip)
and steganography algorithms here: [SUniward](https://dde.binghamton.edu/download/stego_algorithms/download/S-UNIWARD_linux_make_v10.tar.gz), [WOW](https://dde.binghamton.edu/download/stego_algorithms/download/WOW_linux_make_v10.tar.gz), and [MiPOD](https://dde.binghamton.edu/download/stego_algorithms/download/MiPOD_matlab.zip).
Create corresponding stego images for each steganography algorithm. Make sure to change random seed for each image to get random key dataset.
